"""Keyword-based query router: classify a query into one or more retrieval sources."""

from __future__ import annotations

import re

from src.types import Source


def _w(kw: str) -> re.Pattern[str]:
    """Whole-word match (word boundaries on both sides)."""
    return re.compile(r"\b" + re.escape(kw) + r"\b", re.IGNORECASE)


def _p(phrase: str) -> re.Pattern[str]:
    """Prefix phrase match (word boundary at start only, phrase must appear verbatim)."""
    return re.compile(r"\b" + re.escape(phrase), re.IGNORECASE)


def _prefix(stem: str) -> re.Pattern[str]:
    """Stem + optional word chars (matches 'competitive', 'competitively', etc.)."""
    return re.compile(r"\b" + re.escape(stem) + r"\w*", re.IGNORECASE)


# ---------------------------------------------------------------------------
# PokeAPI — factual, in-game data: stats, moves, types, abilities, evolution
# ---------------------------------------------------------------------------
_POKEAPI_PATTERNS: tuple[re.Pattern[str], ...] = (
    # ---------- stats ----------
    _w("stat"),
    _w("stats"),
    _w("base"),
    _w("bst"),
    _w("hp"),
    _w("attack"),
    _w("defense"),
    _w("defence"),
    _p("sp. atk"),
    _p("sp. def"),
    _p("special attack"),
    _p("special defense"),
    _p("special defence"),
    _p("special atk"),
    _p("special def"),
    _w("speed"),
    _p("base stat"),
    _p("base stats"),
    _p("stat total"),
    # ---------- types ----------
    _w("type"),
    _w("typing"),
    _w("dual"),
    _w("weakness"),
    _w("weaknesses"),
    _w("weak"),
    _w("resist"),
    _w("resists"),
    _w("resistance"),
    _w("resistances"),
    _w("immunity"),
    _w("immunities"),
    _w("immune"),
    _p("super effective"),
    _p("not very effective"),
    _p("type chart"),
    _p("type matchup"),
    _p("type advantage"),
    # ---------- moves ----------
    _w("move"),
    _w("moves"),
    _w("movelist"),
    _w("movepool"),
    _p("move list"),
    _p("move pool"),
    _w("learn"),
    _w("learns"),
    _w("learnset"),
    _p("level up"),
    _p("level-up"),
    _w("levelup"),
    _p("by level"),
    _p("egg move"),
    _p("egg moves"),
    _p("tutor move"),
    _p("tutor moves"),
    _w("tm"),
    _w("hm"),
    _w("tr"),
    _p("technical machine"),
    _p("technical record"),
    _p("hidden machine"),
    _w("power"),
    _w("accuracy"),
    _w("pp"),
    _p("move category"),
    _p("move effect"),
    _p("move type"),
    # ---------- abilities ----------
    _w("ability"),
    _w("abilities"),
    _p("hidden ability"),
    _p("dream world"),
    _p("ability effect"),
    # ---------- evolution ----------
    _w("evolve"),
    _w("evolves"),
    _w("evolution"),
    _w("prevo"),
    _w("prevolution"),
    _w("unevolved"),
    _w("pre-evolution"),
    _p("evolution chain"),
    _p("evolution line"),
    _p("final form"),
    _p("base form"),
    _p("evolves from"),
    _p("evolves into"),
    _p("trade evolution"),
    _p("stone evolution"),
    _p("friendship evolution"),
    _p("level evolution"),
    # ---------- forms & variants ----------
    _w("form"),
    _w("forms"),
    _w("variant"),
    _w("variants"),
    _w("mega"),
    _w("gigantamax"),
    _w("dynamax"),
    _w("gmax"),
    _w("galarian"),
    _w("alolan"),
    _w("hisuian"),
    _w("paldean"),
    _w("regional"),
    _p("regional form"),
    _p("alternate form"),
    # ---------- breeding / egg ----------
    _p("egg group"),
    _p("egg groups"),
    _w("breedable"),
    _p("can breed"),
    _p("breeding"),
    _p("gender ratio"),
    _w("genderless"),
    _w("undiscovered"),
    # ---------- physical attributes ----------
    _w("height"),
    _w("weight"),
    _p("how tall"),
    _p("how heavy"),
    # ---------- catch & encounter ----------
    _w("catch"),
    _w("catchable"),
    _p("catch rate"),
    _p("capture rate"),
    _p("where to find"),
    _p("where to catch"),
    _p("how to get"),
    _p("how to obtain"),
    _w("location"),
    _w("locations"),
    _w("encounter"),
    _w("encounters"),
    _w("found"),
    _p("found in"),
    _p("wild encounter"),
    _p("spawn"),
    # ---------- leveling / experience ----------
    _w("level"),
    _p("leveling"),
    _p("exp group"),
    _p("experience group"),
    _p("growth rate"),
    _p("base experience"),
    _p("base exp"),
    # ---------- happiness / friendship ----------
    _w("friendship"),
    _w("happiness"),
    _p("base friendship"),
    _p("high friendship"),
    # ---------- dex / classification ----------
    _p("dex number"),
    _p("dex entry"),
    _p("national dex"),
    _p("pokedex number"),
    _w("legendary"),
    _w("mythical"),
    _w("pseudo"),
    _p("pseudo legendary"),
    _w("starter"),
    _w("fossil"),
    # ---------- game mechanics: items / status ----------
    _w("item"),
    _w("items"),
    _w("restore"),
    _w("restores"),
    _w("faint"),
    _w("fainted"),
    _w("nature"),
    _w("natures"),
    _w("berry"),
    _w("berries"),
    _w("held"),
    _p("held item"),
    _w("pokerus"),
)

# ---------------------------------------------------------------------------
# Smogon — competitive: tiers, EVs, sets, strategy, meta
# ---------------------------------------------------------------------------
_SMOGON_PATTERNS: tuple[re.Pattern[str], ...] = (
    # ---------- tiers ----------
    _w("tier"),
    _w("tiers"),
    _w("ou"),
    _w("uu"),
    _w("ru"),
    _w("nu"),
    _w("pu"),
    _w("lc"),
    _w("ubers"),
    _w("ag"),
    _w("nfe"),
    _w("zu"),
    _w("monotype"),
    _w("natdex"),
    _p("nat dex"),
    # ---------- competitive meta ----------
    _prefix("competitive"),
    _w("meta"),
    _w("metagame"),
    _w("vgc"),
    _w("doubles"),
    _w("singles"),
    _w("smogon"),
    _w("ranked"),
    _w("ladder"),
    _w("viability"),
    _p("viability ranking"),
    _w("format"),
    _w("formats"),
    _w("banned"),
    _w("banlist"),
    _p("ban list"),
    _w("suspect"),
    _p("suspect test"),
    # ---------- EVs / IVs / natures ----------
    _w("ev"),
    _w("evs"),
    _p("ev spread"),
    _p("effort value"),
    _p("effort values"),
    _w("iv"),
    _w("ivs"),
    _p("individual value"),
    _p("individual values"),
    _p("perfect ivs"),
    _p("hyper train"),
    _p("hyper training"),
    _w("adamant"),
    _w("modest"),
    _w("timid"),
    _w("jolly"),
    _w("bold"),
    _w("impish"),
    _w("careful"),
    _w("calm"),
    _w("252"),
    _p("max speed"),
    _p("max attack"),
    _p("max spa"),
    _p("speed tier"),
    _p("bulk calc"),
    _p("damage calc"),
    _w("calc"),
    _p("damage roll"),
    # ---------- sets / movesets ----------
    _w("moveset"),
    _w("movesets"),
    _w("set"),
    _w("sets"),
    _p("best set"),
    _p("best moveset"),
    _p("standard set"),
    _p("choice set"),
    _p("lead set"),
    _w("build"),
    _w("builds"),
    _p("how to use"),
    _p("how to run"),
    _p("how to play"),
    # ---------- roles ----------
    _w("sweeper"),
    _w("wallbreaker"),
    _w("wall"),
    _w("tank"),
    _w("pivot"),
    _w("lead"),
    _w("cleaner"),
    _w("revenge"),
    _p("revenge killer"),
    _w("glue"),
    _w("stallbreaker"),
    _p("stall breaker"),
    _w("setup"),
    _p("set up"),
    _p("setup sweeper"),
    _p("physical sweeper"),
    _p("special sweeper"),
    _p("mixed attacker"),
    _w("bulky"),
    _w("offensive"),
    _w("defensive"),
    _w("utility"),
    # ---------- counters / checks ----------
    _w("counter"),
    _w("counters"),
    _w("check"),
    _w("checks"),
    _p("hard counter"),
    _p("soft check"),
    _p("beat"),
    _p("deal with"),
    _p("stop"),
    # ---------- team roles / synergy ----------
    _w("coverage"),
    _w("teammate"),
    _w("teammates"),
    _w("synergy"),
    _w("core"),
    _p("team building"),
    _p("teambuilding"),
    _p("team composition"),
    _p("team comp"),
    _p("balance team"),
    _p("stall team"),
    _p("hyper offense"),
    _p("bulky offense"),
    _p("sun team"),
    _p("rain team"),
    _p("sand team"),
    _p("hail team"),
    _p("trick room team"),
    _p("sample team"),
    # ---------- hazards / field conditions ----------
    _p("stealth rock"),
    _p("entry hazard"),
    _p("entry hazards"),
    _w("hazards"),
    _w("spikes"),
    _p("toxic spikes"),
    _p("sticky web"),
    _p("rapid spin"),
    _w("defog"),
    _p("hazard removal"),
    _p("hazard setter"),
    # ---------- speed / priority ----------
    _w("priority"),
    _p("faster than"),
    _p("outspeed"),
    _p("speed creep"),
    # ---------- weather / terrain ----------
    _w("weather"),
    _p("trick room"),
    _p("sun setter"),
    _p("rain setter"),
    _p("sand setter"),
    _p("snow setter"),
    _w("terrain"),
    _p("electric terrain"),
    _p("psychic terrain"),
    _p("misty terrain"),
    _p("grassy terrain"),
    # ---------- items (competitive framing) ----------
    _p("choice band"),
    _p("choice specs"),
    _p("choice scarf"),
    _w("leftovers"),
    _p("life orb"),
    _p("assault vest"),
    _p("heavy-duty boots"),
    _p("heavy duty boots"),
    _w("boots"),
    _p("rocky helmet"),
    _p("focus sash"),
    _p("black sludge"),
    _w("eviolite"),
    _p("weakness policy"),
    _p("power herb"),
    # ---------- strategies ----------
    _w("strategy"),
    _w("strategies"),
    _w("abuse"),
    _p("set up on"),
    _p("boost"),
    _w("sweep"),
    _p("revenge kill"),
    _p("late game"),
    _p("early game"),
    _p("mid game"),
    _p("win condition"),
    _p("win con"),
    _p("z move"),
    _p("z-move"),
    _w("terastallize"),
    _p("tera type"),
)

# ---------------------------------------------------------------------------
# Bulbapedia — lore, flavor, anime, game history, origins
# ---------------------------------------------------------------------------
_BULBAPEDIA_PATTERNS: tuple[re.Pattern[str], ...] = (
    # ---------- pokedex / flavor ----------
    _w("lore"),
    _p("flavor text"),
    _p("flavour text"),
    _w("pokedex"),
    _p("dex entry"),
    _p("dex entries"),
    _p("pokedex entry"),
    _p("pokedex entries"),
    _p("pokedex description"),
    _w("species"),
    _w("category"),
    # ---------- design / origin ----------
    _w("origin"),
    _w("design"),
    _w("based on"),
    _p("inspired by"),
    _w("mythology"),
    _w("folklore"),
    _w("symbolism"),
    _p("name origin"),
    _w("etymology"),
    _w("backstory"),
    _p("real world"),
    # ---------- anime / manga / media ----------
    _w("anime"),
    _w("manga"),
    _w("episode"),
    _w("debut"),
    _p("first appeared"),
    _p("first appearance"),
    _w("ash"),
    _p("ash's"),
    _w("misty"),
    _w("brock"),
    _w("serena"),
    _w("satoshi"),
    _w("movie"),
    _w("film"),
    _w("animated"),
    _p("pokemon adventures"),
    # ---------- game history / generation ----------
    _w("history"),
    _w("introduced"),
    _w("generation"),
    _w("gen"),
    _p("first game"),
    _p("first appeared in"),
    _p("originally from"),
    _p("originally in"),
    _p("debut game"),
    _p("what game"),
    _p("which game"),
    _p("which generation"),
    _p("what generation"),
    _w("remake"),
    _w("remakes"),
    _w("mainline"),
    # ---------- regions / locations (world-building) ----------
    _w("region"),
    _w("regions"),
    _w("kanto"),
    _w("johto"),
    _w("hoenn"),
    _w("sinnoh"),
    _w("unova"),
    _w("kalos"),
    _w("alola"),
    _w("galar"),
    _w("hisui"),
    _w("paldea"),
    _w("habitat"),
    # ---------- trainers / characters ----------
    _w("gym"),
    _p("gym leader"),
    _p("elite four"),
    _w("champion"),
    _w("rival"),
    _w("professor"),
    _p("team rocket"),
    _p("team magma"),
    _p("team aqua"),
    _p("team galactic"),
    _p("team plasma"),
    _p("team flare"),
    _p("team skull"),
    _p("team yell"),
    # ---------- misc ----------
    _w("cry"),
    _w("footprint"),
    _p("shiny rate"),
    _p("shiny odds"),
    _p("base color"),
    _w("trivia"),
    _p("fun fact"),
    _w("inspired"),
)

_ALL_SOURCES: list[Source] = ["bulbapedia", "pokeapi", "smogon"]

_SOURCE_PATTERNS: dict[Source, tuple[re.Pattern[str], ...]] = {
    "pokeapi": _POKEAPI_PATTERNS,
    "smogon": _SMOGON_PATTERNS,
    "bulbapedia": _BULBAPEDIA_PATTERNS,
}


class QueryRouter:
    def route(self, query: str) -> list[Source]:
        stripped = query.strip()
        if not stripped:
            return list(_ALL_SOURCES)

        matched: list[Source] = []
        for source, patterns in _SOURCE_PATTERNS.items():
            if any(p.search(stripped) for p in patterns):
                matched.append(source)

        if not matched:
            return list(_ALL_SOURCES)

        return sorted(matched)
