"""Keyword-based query router: classify a query into one or more retrieval sources."""

from __future__ import annotations

import re

from src.types import Source


def _whole_word(kw: str) -> re.Pattern[str]:
    """Whole-word match (word boundaries on both sides)."""
    return re.compile(r"\b" + re.escape(kw) + r"\b", re.IGNORECASE)


def _phrase_word_stem(phrase: str) -> re.Pattern[str]:
    """Prefix phrase match (word boundary at start only, phrase must appear verbatim)."""
    return re.compile(r"\b" + re.escape(phrase), re.IGNORECASE)


def _word_stem(stem: str) -> re.Pattern[str]:
    """Stem + optional word chars (matches 'competitive', 'competitively', etc.)."""
    return re.compile(r"\b" + re.escape(stem) + r"\w*", re.IGNORECASE)


# ---------------------------------------------------------------------------
# PokeAPI — factual, in-game data: stats, moves, types, abilities, evolution
# ---------------------------------------------------------------------------
_POKEAPI_PATTERNS: tuple[re.Pattern[str], ...] = (
    # ---------- stats ----------
    _whole_word("stat"),
    _whole_word("stats"),
    _whole_word("base"),
    _whole_word("bst"),
    _whole_word("hp"),
    _whole_word("attack"),
    _whole_word("defense"),
    _whole_word("defence"),
    _phrase_word_stem("sp. atk"),
    _phrase_word_stem("sp. def"),
    _phrase_word_stem("special attack"),
    _phrase_word_stem("special defense"),
    _phrase_word_stem("special defence"),
    _phrase_word_stem("special atk"),
    _phrase_word_stem("special def"),
    _whole_word("speed"),
    _phrase_word_stem("base stat"),
    _phrase_word_stem("base stats"),
    _phrase_word_stem("stat total"),
    # ---------- types ----------
    _whole_word("type"),
    _whole_word("typing"),
    _whole_word("dual"),
    _whole_word("weakness"),
    _whole_word("weaknesses"),
    _whole_word("weak"),
    _whole_word("resist"),
    _whole_word("resists"),
    _whole_word("resistance"),
    _whole_word("resistances"),
    _whole_word("immunity"),
    _whole_word("immunities"),
    _whole_word("immune"),
    _phrase_word_stem("super effective"),
    _phrase_word_stem("not very effective"),
    _phrase_word_stem("type chart"),
    _phrase_word_stem("type matchup"),
    _phrase_word_stem("type advantage"),
    # ---------- moves ----------
    _whole_word("move"),
    _whole_word("moves"),
    _whole_word("movelist"),
    _whole_word("movepool"),
    _phrase_word_stem("move list"),
    _phrase_word_stem("move pool"),
    _whole_word("learn"),
    _whole_word("learns"),
    _whole_word("learnset"),
    _phrase_word_stem("level up"),
    _phrase_word_stem("level-up"),
    _whole_word("levelup"),
    _phrase_word_stem("by level"),
    _phrase_word_stem("egg move"),
    _phrase_word_stem("egg moves"),
    _phrase_word_stem("tutor move"),
    _phrase_word_stem("tutor moves"),
    _whole_word("tm"),
    _whole_word("hm"),
    _whole_word("tr"),
    _phrase_word_stem("technical machine"),
    _phrase_word_stem("technical record"),
    _phrase_word_stem("hidden machine"),
    _whole_word("power"),
    _whole_word("accuracy"),
    _whole_word("pp"),
    _phrase_word_stem("move category"),
    _phrase_word_stem("move effect"),
    _phrase_word_stem("move type"),
    # ---------- abilities ----------
    _whole_word("ability"),
    _whole_word("abilities"),
    _phrase_word_stem("hidden ability"),
    _phrase_word_stem("dream world"),
    _phrase_word_stem("ability effect"),
    # ---------- evolution ----------
    _whole_word("evolve"),
    _whole_word("evolves"),
    _whole_word("evolution"),
    _whole_word("prevo"),
    _whole_word("prevolution"),
    _whole_word("unevolved"),
    _whole_word("pre-evolution"),
    _phrase_word_stem("evolution chain"),
    _phrase_word_stem("evolution line"),
    _phrase_word_stem("final form"),
    _phrase_word_stem("base form"),
    _phrase_word_stem("evolves from"),
    _phrase_word_stem("evolves into"),
    _phrase_word_stem("trade evolution"),
    _phrase_word_stem("stone evolution"),
    _phrase_word_stem("friendship evolution"),
    _phrase_word_stem("level evolution"),
    # ---------- forms & variants ----------
    _whole_word("form"),
    _whole_word("forms"),
    _whole_word("variant"),
    _whole_word("variants"),
    _whole_word("mega"),
    _whole_word("gigantamax"),
    _whole_word("dynamax"),
    _whole_word("gmax"),
    _whole_word("galarian"),
    _whole_word("alolan"),
    _whole_word("hisuian"),
    _whole_word("paldean"),
    _whole_word("regional"),
    _phrase_word_stem("regional form"),
    _phrase_word_stem("alternate form"),
    # ---------- breeding / egg ----------
    _phrase_word_stem("egg group"),
    _phrase_word_stem("egg groups"),
    _whole_word("breedable"),
    _phrase_word_stem("can breed"),
    _phrase_word_stem("breeding"),
    _phrase_word_stem("gender ratio"),
    _whole_word("genderless"),
    _whole_word("undiscovered"),
    # ---------- physical attributes ----------
    _whole_word("height"),
    _whole_word("weight"),
    _phrase_word_stem("how tall"),
    _phrase_word_stem("how heavy"),
    # ---------- catch & encounter ----------
    _whole_word("catch"),
    _whole_word("catchable"),
    _phrase_word_stem("catch rate"),
    _phrase_word_stem("capture rate"),
    _phrase_word_stem("where to find"),
    _phrase_word_stem("where to catch"),
    _phrase_word_stem("how to get"),
    _phrase_word_stem("how to obtain"),
    _whole_word("location"),
    _whole_word("locations"),
    _whole_word("encounter"),
    _whole_word("encounters"),
    _whole_word("found"),
    _phrase_word_stem("found in"),
    _phrase_word_stem("wild encounter"),
    _phrase_word_stem("spawn"),
    # ---------- leveling / experience ----------
    _whole_word("level"),
    _phrase_word_stem("leveling"),
    _phrase_word_stem("exp group"),
    _phrase_word_stem("experience group"),
    _phrase_word_stem("growth rate"),
    _phrase_word_stem("base experience"),
    _phrase_word_stem("base exp"),
    # ---------- happiness / friendship ----------
    _whole_word("friendship"),
    _whole_word("happiness"),
    _phrase_word_stem("base friendship"),
    _phrase_word_stem("high friendship"),
    # ---------- dex / classification ----------
    _phrase_word_stem("dex number"),
    _phrase_word_stem("dex entry"),
    _phrase_word_stem("national dex"),
    _phrase_word_stem("pokedex number"),
    _whole_word("legendary"),
    _whole_word("mythical"),
    _whole_word("pseudo"),
    _phrase_word_stem("pseudo legendary"),
    _whole_word("starter"),
    _whole_word("fossil"),
    # ---------- game mechanics: items / status ----------
    _whole_word("item"),
    _whole_word("items"),
    _whole_word("restore"),
    _whole_word("restores"),
    _whole_word("faint"),
    _whole_word("fainted"),
    _whole_word("nature"),
    _whole_word("natures"),
    _whole_word("berry"),
    _whole_word("berries"),
    _whole_word("held"),
    _phrase_word_stem("held item"),
    _whole_word("pokerus"),
)

# ---------------------------------------------------------------------------
# Smogon — competitive: tiers, EVs, sets, strategy, meta
# ---------------------------------------------------------------------------
_SMOGON_PATTERNS: tuple[re.Pattern[str], ...] = (
    # ---------- tiers ----------
    _whole_word("tier"),
    _whole_word("tiers"),
    _whole_word("ou"),
    _whole_word("uu"),
    _whole_word("ru"),
    _whole_word("nu"),
    _whole_word("pu"),
    _whole_word("lc"),
    _whole_word("ubers"),
    _whole_word("ag"),
    _whole_word("nfe"),
    _whole_word("zu"),
    _whole_word("monotype"),
    _whole_word("natdex"),
    _phrase_word_stem("nat dex"),
    # ---------- competitive meta ----------
    _word_stem("competitive"),
    _whole_word("meta"),
    _whole_word("metagame"),
    _whole_word("vgc"),
    _whole_word("doubles"),
    _whole_word("singles"),
    _whole_word("smogon"),
    _whole_word("ranked"),
    _whole_word("ladder"),
    _whole_word("viability"),
    _phrase_word_stem("viability ranking"),
    _whole_word("format"),
    _whole_word("formats"),
    _whole_word("banned"),
    _whole_word("banlist"),
    _phrase_word_stem("ban list"),
    _whole_word("suspect"),
    _phrase_word_stem("suspect test"),
    # ---------- EVs / IVs / natures ----------
    _whole_word("ev"),
    _whole_word("evs"),
    _phrase_word_stem("ev spread"),
    _phrase_word_stem("effort value"),
    _phrase_word_stem("effort values"),
    _whole_word("iv"),
    _whole_word("ivs"),
    _phrase_word_stem("individual value"),
    _phrase_word_stem("individual values"),
    _phrase_word_stem("perfect ivs"),
    _phrase_word_stem("hyper train"),
    _phrase_word_stem("hyper training"),
    _whole_word("adamant"),
    _whole_word("modest"),
    _whole_word("timid"),
    _whole_word("jolly"),
    _whole_word("bold"),
    _whole_word("impish"),
    _whole_word("careful"),
    _whole_word("calm"),
    _whole_word("252"),
    _phrase_word_stem("max speed"),
    _phrase_word_stem("max attack"),
    _phrase_word_stem("max spa"),
    _phrase_word_stem("speed tier"),
    _phrase_word_stem("bulk calc"),
    _phrase_word_stem("damage calc"),
    _whole_word("calc"),
    _phrase_word_stem("damage roll"),
    # ---------- sets / movesets ----------
    _whole_word("moveset"),
    _whole_word("movesets"),
    _whole_word("set"),
    _whole_word("sets"),
    _phrase_word_stem("best set"),
    _phrase_word_stem("best moveset"),
    _phrase_word_stem("standard set"),
    _phrase_word_stem("choice set"),
    _phrase_word_stem("lead set"),
    _whole_word("build"),
    _whole_word("builds"),
    _phrase_word_stem("how to use"),
    _phrase_word_stem("how to run"),
    _phrase_word_stem("how to play"),
    # ---------- roles ----------
    _whole_word("sweeper"),
    _whole_word("wallbreaker"),
    _whole_word("wall"),
    _whole_word("tank"),
    _whole_word("pivot"),
    _whole_word("lead"),
    _whole_word("cleaner"),
    _whole_word("revenge"),
    _phrase_word_stem("revenge killer"),
    _whole_word("glue"),
    _whole_word("stallbreaker"),
    _phrase_word_stem("stall breaker"),
    _whole_word("setup"),
    _phrase_word_stem("set up"),
    _phrase_word_stem("setup sweeper"),
    _phrase_word_stem("physical sweeper"),
    _phrase_word_stem("special sweeper"),
    _phrase_word_stem("mixed attacker"),
    _whole_word("bulky"),
    _whole_word("offensive"),
    _whole_word("defensive"),
    _whole_word("utility"),
    # ---------- counters / checks ----------
    _whole_word("counter"),
    _whole_word("counters"),
    _whole_word("check"),
    _whole_word("checks"),
    _phrase_word_stem("hard counter"),
    _phrase_word_stem("soft check"),
    _phrase_word_stem("beat"),
    _phrase_word_stem("deal with"),
    _phrase_word_stem("stop"),
    # ---------- team roles / synergy ----------
    _whole_word("coverage"),
    _whole_word("teammate"),
    _whole_word("teammates"),
    _whole_word("synergy"),
    _whole_word("core"),
    _phrase_word_stem("team building"),
    _phrase_word_stem("teambuilding"),
    _phrase_word_stem("team composition"),
    _phrase_word_stem("team comp"),
    _phrase_word_stem("balance team"),
    _phrase_word_stem("stall team"),
    _phrase_word_stem("hyper offense"),
    _phrase_word_stem("bulky offense"),
    _phrase_word_stem("sun team"),
    _phrase_word_stem("rain team"),
    _phrase_word_stem("sand team"),
    _phrase_word_stem("hail team"),
    _phrase_word_stem("trick room team"),
    _phrase_word_stem("sample team"),
    # ---------- hazards / field conditions ----------
    _phrase_word_stem("stealth rock"),
    _phrase_word_stem("entry hazard"),
    _phrase_word_stem("entry hazards"),
    _whole_word("hazards"),
    _whole_word("spikes"),
    _phrase_word_stem("toxic spikes"),
    _phrase_word_stem("sticky web"),
    _phrase_word_stem("rapid spin"),
    _whole_word("defog"),
    _phrase_word_stem("hazard removal"),
    _phrase_word_stem("hazard setter"),
    # ---------- speed / priority ----------
    _whole_word("priority"),
    _phrase_word_stem("faster than"),
    _phrase_word_stem("outspeed"),
    _phrase_word_stem("speed creep"),
    # ---------- weather / terrain ----------
    _whole_word("weather"),
    _phrase_word_stem("trick room"),
    _phrase_word_stem("sun setter"),
    _phrase_word_stem("rain setter"),
    _phrase_word_stem("sand setter"),
    _phrase_word_stem("snow setter"),
    _whole_word("terrain"),
    _phrase_word_stem("electric terrain"),
    _phrase_word_stem("psychic terrain"),
    _phrase_word_stem("misty terrain"),
    _phrase_word_stem("grassy terrain"),
    # ---------- items (competitive framing) ----------
    _phrase_word_stem("choice band"),
    _phrase_word_stem("choice specs"),
    _phrase_word_stem("choice scarf"),
    _whole_word("leftovers"),
    _phrase_word_stem("life orb"),
    _phrase_word_stem("assault vest"),
    _phrase_word_stem("heavy-duty boots"),
    _phrase_word_stem("heavy duty boots"),
    _whole_word("boots"),
    _phrase_word_stem("rocky helmet"),
    _phrase_word_stem("focus sash"),
    _phrase_word_stem("black sludge"),
    _whole_word("eviolite"),
    _phrase_word_stem("weakness policy"),
    _phrase_word_stem("power herb"),
    # ---------- strategies ----------
    _whole_word("strategy"),
    _whole_word("strategies"),
    _whole_word("abuse"),
    _phrase_word_stem("set up on"),
    _phrase_word_stem("boost"),
    _whole_word("sweep"),
    _phrase_word_stem("revenge kill"),
    _phrase_word_stem("late game"),
    _phrase_word_stem("early game"),
    _phrase_word_stem("mid game"),
    _phrase_word_stem("win condition"),
    _phrase_word_stem("win con"),
    _phrase_word_stem("z move"),
    _phrase_word_stem("z-move"),
    _whole_word("terastallize"),
    _phrase_word_stem("tera type"),
)

# ---------------------------------------------------------------------------
# Bulbapedia — lore, flavor, anime, game history, origins
# ---------------------------------------------------------------------------
_BULBAPEDIA_PATTERNS: tuple[re.Pattern[str], ...] = (
    # ---------- pokedex / flavor ----------
    _whole_word("lore"),
    _phrase_word_stem("flavor text"),
    _phrase_word_stem("flavour text"),
    _whole_word("pokedex"),
    _phrase_word_stem("dex entry"),
    _phrase_word_stem("dex entries"),
    _phrase_word_stem("pokedex entry"),
    _phrase_word_stem("pokedex entries"),
    _phrase_word_stem("pokedex description"),
    _whole_word("species"),
    _whole_word("category"),
    # ---------- design / origin ----------
    _whole_word("origin"),
    _whole_word("design"),
    _whole_word("based on"),
    _phrase_word_stem("inspired by"),
    _whole_word("mythology"),
    _whole_word("folklore"),
    _whole_word("symbolism"),
    _phrase_word_stem("name origin"),
    _whole_word("etymology"),
    _whole_word("backstory"),
    _phrase_word_stem("real world"),
    # ---------- anime / manga / media ----------
    _whole_word("anime"),
    _whole_word("manga"),
    _whole_word("episode"),
    _whole_word("debut"),
    _phrase_word_stem("first appeared"),
    _phrase_word_stem("first appearance"),
    _whole_word("ash"),
    _phrase_word_stem("ash's"),
    _whole_word("misty"),
    _whole_word("brock"),
    _whole_word("serena"),
    _whole_word("satoshi"),
    _whole_word("movie"),
    _whole_word("film"),
    _whole_word("animated"),
    _phrase_word_stem("pokemon adventures"),
    # ---------- game history / generation ----------
    _whole_word("history"),
    _whole_word("introduced"),
    _whole_word("generation"),
    _whole_word("gen"),
    _phrase_word_stem("first game"),
    _phrase_word_stem("first appeared in"),
    _phrase_word_stem("originally from"),
    _phrase_word_stem("originally in"),
    _phrase_word_stem("debut game"),
    _phrase_word_stem("what game"),
    _phrase_word_stem("which game"),
    _phrase_word_stem("which generation"),
    _phrase_word_stem("what generation"),
    _whole_word("remake"),
    _whole_word("remakes"),
    _whole_word("mainline"),
    # ---------- regions / locations (world-building) ----------
    _whole_word("region"),
    _whole_word("regions"),
    _whole_word("kanto"),
    _whole_word("johto"),
    _whole_word("hoenn"),
    _whole_word("sinnoh"),
    _whole_word("unova"),
    _whole_word("kalos"),
    _whole_word("alola"),
    _whole_word("galar"),
    _whole_word("hisui"),
    _whole_word("paldea"),
    _whole_word("habitat"),
    # ---------- trainers / characters ----------
    _whole_word("gym"),
    _phrase_word_stem("gym leader"),
    _phrase_word_stem("elite four"),
    _whole_word("champion"),
    _whole_word("rival"),
    _whole_word("professor"),
    _phrase_word_stem("team rocket"),
    _phrase_word_stem("team magma"),
    _phrase_word_stem("team aqua"),
    _phrase_word_stem("team galactic"),
    _phrase_word_stem("team plasma"),
    _phrase_word_stem("team flare"),
    _phrase_word_stem("team skull"),
    _phrase_word_stem("team yell"),
    # ---------- misc ----------
    _whole_word("cry"),
    _whole_word("footprint"),
    _phrase_word_stem("shiny rate"),
    _phrase_word_stem("shiny odds"),
    _phrase_word_stem("base color"),
    _whole_word("trivia"),
    _phrase_word_stem("fun fact"),
    _whole_word("inspired"),
)

_ALL_SOURCES: list[Source] = ["bulbapedia", "pokeapi", "smogon"]

_SOURCE_PATTERNS: dict[Source, tuple[re.Pattern[str], ...]] = {
    "pokeapi": _POKEAPI_PATTERNS,
    "smogon": _SMOGON_PATTERNS,
    "bulbapedia": _BULBAPEDIA_PATTERNS,
}


class QueryRouter:
    def route(self, query: str) -> list[Source]:
        stripped = query.strip()
        if not stripped:
            return list(_ALL_SOURCES)

        matched: list[Source] = []
        for source, patterns in _SOURCE_PATTERNS.items():
            if any(p.search(stripped) for p in patterns):
                matched.append(source)

        if not matched:
            return list(_ALL_SOURCES)

        return sorted(matched)
